name: Update Weather Image

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Explicitly setting version 3.12.5
          python-version: '3.12.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests Pillow

      - name: Produce Camera Images
        run: python ./scripts/CameraScript.py

      - name: Commit to the main image
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/latest_weather_stamped.jpg
          # The 'exit 0' prevents the job from failing if there are no image changes
          git commit -m "Update weather image: $(date)" || exit 0
          git push
