name: Radar Map CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      # 3️⃣ Install system dependencies for Cartopy/MetPy
      - name: Install minimal system dependencies
        run: |
                sudo apt-get update
                sudo apt-get install -y \
                  python3-dev \
                  python3-pip \
                  build-essential \
                  libgeos-dev \
                  libproj-dev \
                  libfreetype6-dev \
                  libpng-dev \
                  libjpeg-dev \
                  libtiff-dev \
                  libblas-dev \
                  liblapack-dev




      # 4️⃣ Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 5️⃣ Install Python packages
      - name: Install Python dependencies
        run: |
          pip install -r scripts/requirements.txt

      # 6️⃣ Run radar map script
      - name: Run Radar Map
        run: python scripts/radarmap.py

