name: Generate Radar Map

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
              sudo apt-get update
              sudo apt-get install -y libgeos-dev libproj-dev gdal-bin libgdal-dev


      - name: Set CARTOPY_DATA_DIR environment variable
        run: echo "CARTOPY_DATA_DIR=./rootrepo/cartopy_data/" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r scripts/requirements.txt

      - name: Generate Radar Map
        run: python scripts/radarmap.py

      - name: Add new radar image
        run: git add docs/radar_maps/*.png

      - name: Commit and push generated maps
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update radar maps" || echo "No changes to commit"
          git push
        continue-on-error: true
