name: Radar Map CI

on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3️⃣ Install minimal system dependencies
      - name: Install system dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y \
                python3-dev \
                python3-pip \
                build-essential \
                libgeos-dev \
                libproj-dev \
                libfreetype6-dev \
                libpng-dev \
                libjpeg-dev \
                libtiff-dev \
                libblas-dev \
                liblapack-dev

      # 4️⃣ Upgrade pip and install Python dependencies
      - name: Install Python dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      # 5️⃣ Run radar map script
      - name: Generate Radar Map
        run: python scripts/radarmap.py

      # 6️⃣ Add generated radar map to Git
      - name: Add new radar map
        run: git add docs/radar_maps/KMOB_radar.png

      # 7️⃣ Commit and push radar map
      - name: Commit and push radar map
        run: |
             git config --global user.name "github-actions[bot]"
             git config --global user.email "github-actions[bot]@users.noreply.github.com"
             git fetch origin master
             git rebase origin/master
             git commit -m "Update radar map" || echo "No changes to commit"
             git push origin HEAD:master
             continue-on-error: true
