name: Generate NEXRAD Radar Map

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set CARTOPY_DATA_DIR environment variable
      run: echo "CARTOPY_DATA_DIR=./rootrepo/cartopy_data/" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Generate Radar Map
      run: python scripts/radarmap.py

    - name: Add new radar map
      run: git add docs/radar_maps/*.png

    - name: Commit and push generated radar map
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "Update radar map" || echo "No changes to commit"
        git push
      continue-on-error: true
