name: Generate Lightning Map

on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: Generate Lightning Sector Maps
      run: python scripts/generate_sector_maps.py

    - name: Add new lightning sector maps
      run: git add docs/lightning_maps/*.png

    - name: Commit and push generated maps
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "Update lightning sector maps" || echo "No changes to commit"
        git push
      continue-on-error: true
